lesson-1-9
SvetlanaBeynik/react-todo pull request #9
Opened 2023-05-24 01:47 UTC by SvetlanaBeynik

lesson-1-9 is completed.

2023-05-27 01:03 UTC, viniciuspietscher requested changes
Hi Svetlana! Great job with the routing!

I requested some changes because we should have two routes, one for `"/"` that will have all your components, and another route for `"/new"` that will only have the h1 with "New Todo List".

At the end you should be able to visit `http://localhost:3000/` and see your list with the input field, and if you visit `http://localhost:3000/new` you will see only the h1 with "New Todo List".

Let me know on slack if you have any questions or need help.

2023-05-27 01:03 UTC, viniciuspietscher commented on src/App.js
> +          path="/new"
This route path should be only `"/"`

2023-05-27 01:03 UTC, viniciuspietscher commented on src/App.js
> +                <h1>New Todo List</h1>
Create a new route for `"/new"` and add this h1 to it

2023-05-30 13:01 UTC, SvetlanaBeynik commented on src/App.js
> +          path="/new"
The pull request is update

2023-05-30 23:22 UTC, viniciuspietscher approved these changes
Great job!!! Thank you for making the changes! 💯 🥇

2023-06-02 12:51 UTC, merged

2023-06-02 12:52 UTC, SvetlanaBeynik commented
Lesson-1-9 done